# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c921023da4de961fed986fb72687b4640b1c416aedae858aaed475aafe107dd83a228af5c51db1ff8bd3762a38e41dc38a04733228c7125da65e412495fcbfc4

test:
  secret_key_base: 5a7b8a22f93cb6bb9ef0c498bdb4dc9bddc265127afb10d4b2e0ca865f1c657a138fcffdbc6fbdc138eab28cde6e50e05908bbc355709fbeb1618c2ea527c16b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
